from fuzzy_match import algorithims as fuz
from fuzzy_match import match


def main():
    res = match.extract("", gemNames, limit=15, score_cutoff=0.125) # type: ignore
    for r in res:
        print("{:20} {:6.3f}%".format(r[0], 100*r[1]))


def valueAll(s1: str, s2: str):
    return (
        fuz.jaro_winkler(s1, s2),
        fuz.cosine(s1, s2),
        fuz.levenshtein(s1, s2),
        fuz.jaro_winkler(s1, s2),
    )


gemNames = [
    "Animate Weapon",
    "Arctic Armour",
    "Artillery Ballista",
    "Barrage",
    "Bear Trap",
    "Blade Blast",
    "Blade Flurry",
    "Blade Vortex",
    "Bladefall",
    "Blast Rain",
    "Blink Arrow",
    "Blood Rage",
    "Burning Arrow",
    "Caustic Arrow",
    "Charged Dash",
    "Cobra Lash",
    "Cremation",
    "Cyclone",
    "Dash",
    "Desecrate",
    "Detonate Dead",
    "Double Strike",
    "Dual Strike",
    "Elemental Hit",
    "Ensnaring Arrow",
    "Ethereal Knives",
    "Explosive Arrow",
    "Explosive Trap",
    "Fire Trap",
    "Flamethrower Trap",
    "Flicker Strike",
    "Frenzy",
    "Frost Blades",
    "Galvanic Arrow",
    "Grace",
    "Haste",
    "Hatred",
    "Herald of Agony",
    "Herald of Ice",
    "Ice Shot",
    "Ice Trap",
    "Lacerate",
    "Lancing Steel",
    "Lightning Arrow",
    "Lightning Strike",
    "Mirror Arrow",
    "Pestilent Strike",
    "Phase Run",
    "Plague Bearer",
    "Poacher's Mark",
    "Precision",
    "Puncture",
    "Purity of Ice",
    "Rain of Arrows",
    "Reave",
    "Riposte",
    "Scourge Arrow",
    "Seismic Trap",
    "Shattering Steel",
    "Shrapnel Ballista",
    "Siege Ballista",
    "Smoke Mine",
    "Sniper's Mark",
    "Spectral Shield Throw",
    "Spectral Throw",
    "Split Arrow",
    "Splitting Steel",
    "Summon Ice Golem",
    "Temporal Chains",
    "Tornado Shot",
    "Toxic Rain",
    "Unearth",
    "Vaal Blade Vortex",
    "Vaal Burning Arrow",
    "Vaal Cyclone",
    "Vaal Detonate Dead",
    "Vaal Double Strike",
    "Vaal Grace",
    "Vaal Haste",
    "Vaal Impurity of Ice",
    "Vaal Lightning Strike",
    "Vaal Rain of Arrows",
    "Vaal Reave",
    "Vaal Spectral Throw",
    "Venom Gyre",
    "Viper Strike",
    "Volatile Dead",
    "Whirling Blades",
    "Wild Strike",
    "Withering Step",
    "Ancestral Cry",
    "Ancestral Protector",
    "Ancestral Warchief",
    "Anger",
    "Animate Guardian",
    "Berserk",
    "Bladestorm",
    "Blood and Sand",
    "Chain Hook",
    "Cleave",
    "Consecrated Path",
    "Decoy Totem",
    "Determination",
    "Devouring Totem",
    "Dominating Blow",
    "Dread Banner",
    "Earthquake",
    "Earthshatter",
    "Enduring Cry",
    "Exsanguinate",
    "Flesh and Stone",
    "General's Cry",
    "Glacial Hammer",
    "Ground Slam",
    "Heavy Strike",
    "Herald of Ash",
    "Herald of Purity",
    "Holy Flame Totem",
    "Ice Crash",
    "Immortal Call",
    "Infernal Blow",
    "Infernal Cry",
    "Intimidating Cry",
    "Leap Slam",
    "Molten Shell",
    "Molten Strike",
    "Perforate",
    "Petrified Blood",
    "Pride",
    "Punishment",
    "Purity of Fire",
    "Rallying Cry",
    "Reap",
    "Reckoning",
    "Rejuvenation Totem",
    "Searing Bond",
    "Seismic Cry",
    "Shield Charge",
    "Shockwave Totem",
    "Smite",
    "Static Strike",
    "Steelskin",
    "Summon Flame Golem",
    "Summon Stone Golem",
    "Sunder",
    "Sweep",
    "Tectonic Slam",
    "Vaal Ancestral Warchief",
    "Vaal Earthquake",
    "Vaal Glacial Hammer",
    "Vaal Ground Slam",
    "Vaal Impurity of Fire",
    "Vaal Molten Shell",
    "Vengeance",
    "Vigilant Strike",
    "Vitality",
    "Vulnerability",
    "War Banner",
    "Warlord's Mark",
    "Arc",
    "Arcane Cloak",
    "Arcanist Brand",
    "Armageddon Brand",
    "Assassin's Mark",
    "Ball Lightning",
    "Bane",
    "Blazing Salvo",
    "Blight",
    "Bodyswap",
    "Bone Offering",
    "Brand Recall",
    "Clarity",
    "Cold Snap",
    "Conductivity",
    "Contagion",
    "Conversion Trap",
    "Convocation",
    "Crackling Lance",
    "Creeping Frost",
    "Dark Pact",
    "Despair",
    "Discharge",
    "Discipline",
    "Divine Ire",
    "Elemental Weakness",
    "Enfeeble",
    "Essence Drain",
    "Fireball",
    "Firestorm",
    "Flame Dash",
    "Flame Surge",
    "Flame Wall",
    "Flameblast",
    "Flammability",
    "Flesh Offering",
    "Freezing Pulse",
    "Frost Bomb",
    "Frost Shield",
    "Frost Wall",
    "Frostbite",
    "Frostblink",
    "Frostbolt",
    "Glacial Cascade",
    "Herald of Thunder",
    "Hexblast",
    "Hydrosphere",
    "Ice Nova",
    "Ice Spear",
    "Icicle Mine",
    "Incinerate",
    "Kinetic Blast",
    "Kinetic Bolt",
    "Lightning Spire Trap",
    "Lightning Tendrils",
    "Lightning Trap",
    "Lightning Warp",
    "Malevolence",
    "Orb of Storms",
    "Penance Brand",
    "Power Siphon",
    "Purifying Flame",
    "Purity of Elements",
    "Purity of Lightning",
    "Pyroclast Mine",
    "Raise Spectre",
    "Raise Zombie",
    "Righteous Fire",
    "Rolling Magma",
    "Scorching Ray",
    "Shock Nova",
    "Sigil of Power",
    "Siphoning Trap",
    "Soulrend",
    "Spark",
    "Spellslinger",
    "Spirit Offering",
    "Storm Brand",
    "Storm Burst",
    "Storm Call",
    "Stormbind",
    "Stormblast Mine",
    "Summon Carrion Golem",
    "Summon Chaos Golem",
    "Summon Holy Relic",
    "Summon Lightning Golem",
    "Summon Raging Spirit",
    "Summon Skeletons",
    "Summon Skitterbots",
    "Tempest Shield",
    "Vaal Arc",
    "Vaal Blight",
    "Vaal Clarity",
    "Vaal Cold Snap",
    "Vaal Discipline",
    "Vaal Fireball",
    "Vaal Flameblast",
    "Vaal Ice Nova",
    "Vaal Impurity of Lightning",
    "Vaal Lightning Trap",
    "Vaal Power Siphon",
    "Vaal Righteous Fire",
    "Vaal Spark",
    "Vaal Storm Call",
    "Vaal Summon Skeletons",
    "Void Sphere",
    "Vortex",
    "Wave of Conviction",
    "Winter Orb",
    "Wintertide Brand",
    "Wither",
    "Wrath",
    "Zealotry",
    "Detonate Mines",
    "Portal",
    "Vaal Breach",
]
main()
